version: 2
updates:
  # Maintain dependencies for npm backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain dependencies for npm frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
